project:
  type: website

website:
  title: "Bennett Kedrosky"
  favicon: flaticon.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: interviews.qmd
        text: Interviews
      - href: courses.qmd
        text: Courses

format:
  html:
    theme:
      light: flatly
      dark: flatly
    css: styles.css
    toc: true
    link-external-newwindow: true
    
    
execute:
  freeze: auto



